### ISSUE TITLE
[bug ] i cant load a cog 

### ISSUE THREAD

**Issue by kpopdev** [MxsicXYZ/Lewds-Cogs#1]
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]: Traceback (most recent call last):
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 171, in _load
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:     await bot.load_extension(spec)
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 1355, in load_extension
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:     lib = spec.loader.load_module()
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap_external>", line 962, in load_module
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap_external>", line 787, in load_module
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap>", line 702, in _load
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/weverse/__init__.py", line 2, in <module>
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:     from .weverse import Weverse
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/weverse/weverse.py", line 33
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:     channel_id = ctx.channel.id
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]:     ^
Jun 11 16:12:52 vmi538808.contaboserver.net python[4977]: SyntaxError: invalid syntax

**Comment by kpopdev** [comment]
@Xynnix pls help <3
